-- GivahBz: Demo campaign data (8 campaigns)
--
-- HOW TO RUN (choose one):
--
-- 1) From project (recommended):  npm run seed
--    Uses SUPABASE_SERVICE_ROLE_KEY from .env and inserts via Supabase client.
--
-- 2) In Supabase Dashboard: SQL Editor → New query → paste this file → Run.
--    Ensure the initial migration has been run first (supabase/migrations/20260223000000_initial.sql).
--
-- Safe to re-run: ON CONFLICT (id) DO NOTHING (SQL) / upsert (npm run seed).
--
-- Optional: clear existing demo campaigns before re-seed (uncomment to use):
-- DELETE FROM public.campaigns WHERE creator_id IS NULL AND (title LIKE '%Maria%' OR title LIKE '%Hurricane%' OR title LIKE '%School Supplies%' OR title LIKE '%Carlos%' OR title LIKE '%Community Center%' OR title LIKE '%Elderly%' OR title LIKE '%Fire Recovery%' OR title LIKE '%Youth Sports%');

INSERT INTO public.campaigns (
  id, title, description, full_description, creator, creator_type, creator_id,
  goal, raised, backers, days_left, category, image, image2, location,
  status, verified, admin_backed, created_at, updated_at
) VALUES
(
  'a1b2c3d4-0001-4000-8000-000000000001',
  'Medical Treatment for Maria''s Daughter',
  'Urgent funds needed for 8-year-old Maria''s daughter who requires specialized surgery at KHMH. Family cannot afford the medical expenses.',
  'Maria''s 8-year-old daughter was recently diagnosed with a congenital heart condition that requires immediate surgery. The family has exhausted their savings and insurance coverage. The surgery must be performed at Karl Heusner Memorial Hospital (KHMH) in Belize City. We are seeking support from the Belizean community to help cover the medical expenses, hospital stay, and post-operative care. Any contribution, no matter how small, will make a difference in this child''s life.',
  'Maria Gonzalez',
  'individual',
  NULL,
  5000,
  2920,
  142,
  12,
  'Medical',
  'https://picsum.photos/seed/medical1/800/600',
  NULL,
  'Belize City, Belize',
  'live',
  true,
  false,
  '2026-02-05T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0002-4000-8000-000000000002',
  'Hurricane Relief for Dangriga Community',
  'Rebuilding homes and providing essential supplies for families affected by recent hurricane damage in Dangriga.',
  'The recent hurricane has left many families in Dangriga without homes and basic necessities. Our organization is working to provide immediate relief including food, clean water, temporary shelter, and rebuilding materials. We need your support to help these families get back on their feet. All funds will go directly to purchasing supplies and materials for affected families.',
  'Dangriga Community Relief Organization',
  'organization',
  NULL,
  5000,
  3640,
  234,
  18,
  'Disaster Relief',
  'https://picsum.photos/seed/disaster1/800/600',
  NULL,
  'Dangriga, Belize',
  'live',
  true,
  false,
  '2026-01-28T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0003-4000-8000-000000000003',
  'School Supplies for Rural Toledo District',
  'Providing books, uniforms, and school supplies for 200+ children in rural Toledo District who cannot afford them.',
  'Many children in rural Toledo District are unable to attend school because their families cannot afford basic supplies like books, uniforms, and writing materials. Our charity aims to ensure every child has access to education by providing these essential items. We work directly with schools in the area to identify children in need and distribute supplies at the start of each school year.',
  'Belize Education Foundation',
  'charity',
  NULL,
  3500,
  2275,
  98,
  25,
  'Education',
  'https://picsum.photos/seed/education1/800/600',
  NULL,
  'Toledo District, Belize',
  'live',
  true,
  false,
  '2026-01-30T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0004-4000-8000-000000000004',
  'Emergency Surgery for Carlos',
  'Carlos needs urgent surgery to repair a work-related injury. Without this surgery, he cannot return to work to support his family.',
  'Carlos, a construction worker and father of three, suffered a severe injury on the job that requires immediate surgery. His employer''s insurance has been delayed, and he cannot afford the procedure. Without this surgery, Carlos faces permanent disability and will be unable to provide for his family. We are raising funds to cover the surgery costs and help his family during recovery.',
  'Carlos Mendez',
  'individual',
  NULL,
  4500,
  2550,
  87,
  15,
  'Medical',
  'https://picsum.photos/seed/medical2/800/600',
  NULL,
  'San Ignacio, Cayo District, Belize',
  'live',
  true,
  false,
  '2026-02-01T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0005-4000-8000-000000000005',
  'Community Center Renovation in Orange Walk',
  'Renovating the community center to provide a safe space for youth programs, senior activities, and community events.',
  'Our community center in Orange Walk has served the community for over 30 years but is now in urgent need of repairs. The roof leaks, electrical systems are outdated, and the building is not accessible for people with disabilities. We need funds to renovate the center so it can continue serving as a hub for youth programs, senior activities, and community gatherings. This project will benefit hundreds of families in Orange Walk.',
  'Orange Walk Community Association',
  'organization',
  NULL,
  5000,
  3100,
  156,
  22,
  'Community',
  'https://picsum.photos/seed/community1/800/600',
  NULL,
  'Orange Walk Town, Belize',
  'live',
  true,
  false,
  '2026-01-25T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0006-4000-8000-000000000006',
  'Food Assistance for Elderly in Corozal',
  'Providing monthly food packages and meals for elderly residents in Corozal who are struggling to afford basic nutrition.',
  'Many elderly residents in Corozal are living on fixed incomes that don''t cover basic necessities, especially food. Our program provides monthly food packages and hot meals to seniors in need. We work with local suppliers to ensure fresh, nutritious food reaches those who need it most. Your support helps us maintain this vital program that serves over 100 elderly residents.',
  'Corozal Senior Support Network',
  'charity',
  NULL,
  2500,
  1750,
  78,
  20,
  'Community',
  'https://picsum.photos/seed/community2/800/600',
  NULL,
  'Corozal Town, Belize',
  'live',
  true,
  false,
  '2026-01-27T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0007-4000-8000-000000000007',
  'Fire Recovery for Belize City Family',
  'A family lost their home and belongings in a house fire. Help them rebuild and replace essentials so they can get back on their feet.',
  'Last month a devastating house fire destroyed the home of the Thompson family in Belize City. They lost everything — clothing, furniture, important documents, and their sense of security. The family of five is currently staying with relatives but needs support to secure temporary housing, replace essential items, and begin rebuilding. The community has rallied, and we are grateful for any contribution to help this family recover and find stability again.',
  'Sarah Thompson',
  'individual',
  NULL,
  5000,
  3110,
  189,
  8,
  'Emergency',
  'https://picsum.photos/seed/emergency1/800/600',
  NULL,
  'Belize City, Belize',
  'live',
  true,
  false,
  '2026-02-10T12:00:00Z',
  now()
),
(
  'a1b2c3d4-0008-4000-8000-000000000008',
  'Youth Sports Equipment for Cayo District',
  'Raising funds to provide sports equipment and coaching for underprivileged youth in Cayo, promoting health and teamwork.',
  'Many young people in Cayo District lack access to organized sports and recreational activities. We aim to equip local youth programs with quality sports equipment — footballs, nets, uniforms, and safety gear — and fund trained coaches for after-school programs. Sport builds discipline, teamwork, and confidence. Your support will give hundreds of children a positive outlet and a chance to grow through play.',
  'Cayo Youth Initiative',
  'organization',
  NULL,
  4000,
  2940,
  124,
  14,
  'Community',
  'https://picsum.photos/seed/sports1/800/600',
  NULL,
  'San Ignacio, Cayo District, Belize',
  'live',
  true,
  false,
  '2026-02-08T12:00:00Z',
  now()
)
ON CONFLICT (id) DO NOTHING;
