"use client";

import { useState, useEffect, useCallback } from "react";
import { useThemedModal } from "@/components/ThemedModal";
import { Banknote, CheckCircle, Loader2, X, Download } from "lucide-react";

interface PayoutRow {
  id: string;
  campaignId: string;
  campaignTitle: string;
  raised: number;
  creatorId: string;
  creatorName: string;
  creatorEmail: string;
  bankName: string;
  accountType: string;
  accountNumber: string;
  accountHolderName: string;
  branch: string | null;
  status: string;
  createdAt: string;
}

interface DonationRow {
  id: string;
  campaignId: string;
  amount: number;
  donorEmail: string;
  donorName: string;
  anonymous: boolean;
  method: string;
  status: string;
  createdAt: string;
  referenceNumber?: string;
}

function formatAmount(n: number) {
  return `BZ$${Number(n).toLocaleString()}`;
}

function formatDate(s: string) {
  try {
    return new Date(s).toLocaleDateString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return s;
  }
}

function buildPayoutLetterHtml(p: PayoutRow, donations: DonationRow[]): string {
  const completedDonations = donations.filter((d) => d.status === "completed");
  const totalFromDonations = completedDonations.reduce((sum, d) => sum + d.amount, 0);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payout summary – ${escapeHtml(p.campaignTitle)}</title>
  <style>
    @page { size: letter; margin: 0.75in; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
    body { font-family: system-ui, sans-serif; font-size: 11pt; line-height: 1.4; color: #111; max-width: 8.5in; margin: 0 auto; padding: 0.5in; }
    h1 { font-size: 16pt; margin-bottom: 0.5em; }
    h2 { font-size: 12pt; margin-top: 1em; margin-bottom: 0.25em; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5em; }
    th, td { border: 1px solid #333; padding: 6px 8px; text-align: left; }
    th { background: #f3f4f6; font-weight: 600; }
    .meta { margin: 1em 0; }
    .meta p { margin: 0.25em 0; }
    .amount { font-weight: 600; }
  </style>
</head>
<body>
  <h1>Payout Summary</h1>
  <div class="meta">
    <p><strong>Campaign:</strong> ${escapeHtml(p.campaignTitle)}</p>
    <p><strong>Amount:</strong> <span class="amount">${formatAmount(p.raised)}</span></p>
    <p><strong>Creator:</strong> ${escapeHtml(p.creatorName)} · ${escapeHtml(p.creatorEmail)}</p>
    <p><strong>Bank:</strong> ${escapeHtml(p.bankName)} · ${escapeHtml(p.accountType)}</p>
    <p><strong>Account holder:</strong> ${escapeHtml(p.accountHolderName)}</p>
    <p><strong>Account number:</strong> ${escapeHtml(p.accountNumber)}${p.branch ? ` · Branch: ${escapeHtml(p.branch)}` : ""}</p>
    <p><strong>Status:</strong> ${escapeHtml(p.status)}</p>
    <p><strong>Request date:</strong> ${formatDate(p.createdAt)}</p>
  </div>
  <h2>Payments (donations) received</h2>
  <p>Total from ${completedDonations.length} completed donation(s): ${formatAmount(totalFromDonations)}</p>
  <table>
    <thead>
      <tr><th>Date</th><th>Donor</th><th>Amount</th><th>Method</th><th>Reference</th></tr>
    </thead>
    <tbody>
      ${completedDonations.map((d) => `
      <tr>
        <td>${formatDate(d.createdAt)}</td>
        <td>${d.anonymous ? "Anonymous" : escapeHtml(d.donorName || d.donorEmail || "—")}</td>
        <td class="amount">${formatAmount(d.amount)}</td>
        <td>${escapeHtml(d.method || "—")}</td>
        <td>${escapeHtml(d.referenceNumber || "—")}</td>
      </tr>`).join("")}
    </tbody>
  </table>
  <p style="margin-top: 1em; font-size: 10pt; color: #666;">Generated by GivahBz Admin. Letter size.</p>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export default function AdminPayoutsPage() {
  const { alert } = useThemedModal();
  const [payouts, setPayouts] = useState<PayoutRow[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [completingId, setCompletingId] = useState<string | null>(null);
  const [selectedPayout, setSelectedPayout] = useState<PayoutRow | null>(null);
  const [payoutDonations, setPayoutDonations] = useState<DonationRow[]>([]);
  const [loadingDonations, setLoadingDonations] = useState(false);

  const loadPayouts = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await fetch("/api/admin/payouts", { credentials: "include" });
      if (!res.ok) throw new Error("Failed to load payouts");
      const data = await res.json();
      const sorted = [...(data || [])].sort((a: PayoutRow, b: PayoutRow) => {
        const aPending = a.status === "pending" ? 1 : 0;
        const bPending = b.status === "pending" ? 1 : 0;
        if (bPending !== aPending) return bPending - aPending;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
      setPayouts(sorted);
    } catch (err) {
      console.error("Error loading payouts:", err);
      setPayouts([]);
      alert("Failed to load payouts.", { title: "Error", variant: "error" });
    } finally {
      setIsLoading(false);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps -- loadPayouts intentionally runs once on mount

  useEffect(() => {
    loadPayouts();
  }, [loadPayouts]);

  useEffect(() => {
    if (!selectedPayout) {
      setPayoutDonations([]);
      return;
    }
    let cancelled = false;
    setLoadingDonations(true);
    fetch(`/api/admin/data/donations?campaignId=${encodeURIComponent(selectedPayout.campaignId)}`, { credentials: "include" })
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        if (!cancelled) setPayoutDonations(Array.isArray(data) ? data : []);
      })
      .catch(() => {
        if (!cancelled) setPayoutDonations([]);
      })
      .finally(() => {
        if (!cancelled) setLoadingDonations(false);
      });
    return () => { cancelled = true; };
  }, [selectedPayout]);

  function openPayoutDetail(p: PayoutRow, e: React.MouseEvent) {
    if ((e.target as HTMLElement).closest("button")) return;
    setSelectedPayout(p);
  }

  function downloadPayoutLetter() {
    if (!selectedPayout) return;
    const html = buildPayoutLetterHtml(selectedPayout, payoutDonations);
    const win = window.open("", "_blank", "noopener,noreferrer");
    if (!win) {
      alert("Popup blocked. Allow popups to download the payout letter.", { title: "Download", variant: "info" });
      return;
    }
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => {
      win.print();
      win.close();
    }, 500);
  }

  async function handleComplete(id: string, e: React.MouseEvent) {
    e.stopPropagation();
    setCompletingId(id);
    try {
      const res = await fetch(`/api/admin/payouts/${id}/complete`, {
        method: "POST",
        credentials: "include",
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(typeof data.error === "string" ? data.error : "Failed to complete payout");
      }
      await loadPayouts();
      alert("Payout marked as completed. The creator has been notified by email and in-app.", {
        title: "Completed",
        variant: "success",
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Failed to complete payout";
      alert(msg, { title: "Error", variant: "error" });
    } finally {
      setCompletingId(null);
    }
  }

  const pendingCount = payouts.filter((p) => p.status === "pending").length;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading payouts...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-semibold text-gray-900 flex items-center gap-2">
            <Banknote className="w-8 h-8 text-primary-600" />
            Payouts
          </h1>
          <p className="text-gray-600 mt-1">
            {payouts.length} payout request{payouts.length !== 1 ? "s" : ""} total
            {pendingCount > 0 && (
              <span className="ml-2 text-amber-700 font-medium">
                · {pendingCount} pending
              </span>
            )}
          </p>
        </div>
      </div>

      {payouts.length === 0 ? (
        <div className="bg-white rounded-xl gradient-border-1 p-8 text-center text-gray-500">
          No payout requests yet.
        </div>
      ) : (
        <div className="bg-white rounded-xl gradient-border-1 min-w-0">
          <p className="px-4 py-2 text-xs text-gray-500 border-b border-gray-100 md:sr-only" aria-hidden="true">Scroll horizontally to view all columns.</p>
          <div className="overflow-x-auto min-w-0 w-full" style={{ WebkitOverflowScrolling: "touch" }}>
            <table className="w-full text-sm min-w-[900px] divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Campaign</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Creator</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Bank</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {payouts.map((p) => (
                  <tr
                    key={p.id}
                    className="hover:bg-gray-50/50 cursor-pointer"
                    onClick={(e) => openPayoutDetail(p, e)}
                  >
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span
                        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          p.status === "pending"
                            ? "bg-amber-100 text-amber-800"
                            : p.status === "completed"
                              ? "bg-green-100 text-green-800"
                              : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        {p.status === "pending" && "Pending"}
                        {p.status === "completed" && "Completed"}
                        {p.status === "processing" && "Processing"}
                        {p.status === "rejected" && "Rejected"}
                        {!["pending", "completed", "processing", "rejected"].includes(p.status) && p.status}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-gray-900 font-medium">{p.campaignTitle || "—"}</span>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700 font-medium">
                      {formatAmount(p.raised)}
                    </td>
                    <td className="px-4 py-3">
                      <div className="text-sm text-gray-900">{p.creatorName || "—"}</div>
                      <div className="text-xs text-gray-500">{p.creatorEmail || ""}</div>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-700">
                      <div>{p.bankName} · {p.accountType}</div>
                      <div className="text-xs text-gray-500">
                        {p.accountHolderName} · ****{String(p.accountNumber).slice(-4)}
                        {p.branch ? ` · ${p.branch}` : ""}
                      </div>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-500">
                      {formatDate(p.createdAt)}
                    </td>
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      {p.status === "pending" ? (
                        <button
                          type="button"
                          onClick={(e) => handleComplete(p.id, e)}
                          disabled={completingId !== null}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-green-600 text-white text-sm font-medium hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {completingId === p.id ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <CheckCircle className="w-4 h-4" />
                          )}
                          Mark as completed
                        </button>
                      ) : (
                        <span className="text-gray-400 text-sm">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
