"use client";

import { useState, useEffect, useCallback } from "react";
import { useThemedModal } from "@/components/ThemedModal";
import { Banknote, CheckCircle, Loader2, X, FileDown } from "lucide-react";
import { SITE_DOMAIN } from "@/lib/siteConfig";

interface PayoutRow {
  id: string;
  campaignId: string;
  campaignTitle: string;
  raised: number;
  creatorId: string;
  creatorName: string;
  creatorEmail: string;
  bankName: string;
  accountType: string;
  accountNumber: string;
  accountHolderName: string;
  branch: string | null;
  status: string;
  createdAt: string;
}

interface DonationRow {
  id: string;
  campaignId: string;
  amount: number;
  donorEmail: string;
  donorName: string;
  anonymous: boolean;
  method: string;
  status: string;
  createdAt: string;
  referenceNumber?: string;
}

function formatAmount(n: number) {
  return `BZ$${Number(n).toLocaleString()}`;
}

function formatDate(s: string) {
  try {
    return new Date(s).toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return s;
  }
}

function buildPayoutLetterHtml(p: PayoutRow, donations: DonationRow[]): string {
  const completedDonations = donations.filter((d) => d.status === "completed");
  const totalFromDonations = completedDonations.reduce((sum, d) => sum + d.amount, 0);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payout summary – ${escapeHtml(p.campaignTitle)}</title>
  <style>
    @page { size: letter; margin: 0.75in; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
    body {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 11pt;
      line-height: 1.4;
      color: #111827;
      max-width: 8.5in;
      margin: 0 auto;
    }
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 1.5rem;
      margin-bottom: 0.75rem;
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }
    .logo {
      height: 40px;
      width: auto;
    }
    .site-name {
      font-size: 14pt;
      font-weight: 700;
      color: #059669; /* success-600 / GivahBz green */
    }
    .tagline {
      font-size: 10pt;
      color: #4b5563;
    }
    .contact {
      text-align: right;
      font-size: 9pt;
      color: #4b5563;
    }
    .divider {
      border: 0;
      border-top: 2px solid #059669;
      margin: 0.25rem 0 1rem;
    }
    h1 { font-size: 16pt; margin-bottom: 0.5em; color: #111827; }
    h2 { font-size: 12pt; margin-top: 1em; margin-bottom: 0.25em; color: #111827; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5em; }
    th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }
    th { background: #f3f4f6; font-weight: 600; }
    .meta { margin: 1em 0; }
    .meta p { margin: 0.25em 0; }
    .amount { font-weight: 600; }
    .footer-note {
      margin-top: 1em;
      font-size: 9pt;
      color: #6b7280;
    }
  </style>
</head>
<body>
  <header class="header">
    <div class="brand">
      <img src="/givah-logo.png" alt="GivahBz" class="logo" />
      <div>
        <div class="site-name">GivahBz</div>
        <div class="tagline">Sharing Burdens. Together.</div>
      </div>
    </div>
    <div class="contact">
      <div>${SITE_DOMAIN}</div>
      <div>Belmopan City, Belize</div>
    </div>
  </header>
  <hr class="divider" />
  <h1>Payout Summary</h1>
  <div class="meta">
    <p><strong>Campaign:</strong> ${escapeHtml(p.campaignTitle)}</p>
    <p><strong>Amount:</strong> <span class="amount">${formatAmount(p.raised)}</span></p>
    <p><strong>Creator:</strong> ${escapeHtml(p.creatorName)} · ${escapeHtml(p.creatorEmail)}</p>
    <p><strong>Bank:</strong> ${escapeHtml(p.bankName)} · ${escapeHtml(p.accountType)}</p>
    <p><strong>Account holder:</strong> ${escapeHtml(p.accountHolderName)}</p>
    <p><strong>Account number:</strong> ${escapeHtml(p.accountNumber)}${p.branch ? ` · Branch: ${escapeHtml(p.branch)}` : ""}</p>
    <p><strong>Status:</strong> ${escapeHtml(p.status)}</p>
    <p><strong>Request date:</strong> ${formatDate(p.createdAt)}</p>
  </div>
  <h2>Payments (donations) received</h2>
  <p>Total from ${completedDonations.length} completed donation(s): ${formatAmount(totalFromDonations)}</p>
  <table>
    <thead>
      <tr><th>Date</th><th>Donor</th><th>Amount</th><th>Method</th><th>Reference</th></tr>
    </thead>
    <tbody>
      ${completedDonations.map((d) => `
      <tr>
        <td>${formatDate(d.createdAt)}</td>
        <td>${d.anonymous ? "Anonymous" : escapeHtml(d.donorName || d.donorEmail || "—")}</td>
        <td class="amount">${formatAmount(d.amount)}</td>
        <td>${escapeHtml(d.method || "—")}</td>
        <td>${escapeHtml(d.referenceNumber || "—")}</td>
      </tr>`).join("")}
    </tbody>
  </table>
  <p class="footer-note">Generated by GivahBz Admin on ${formatDate(p.createdAt)}. Default paper size: Letter (8.5&quot; × 11&quot;).</p>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export default function AdminPayoutsPage() {
  const { alert } = useThemedModal();
  const [payouts, setPayouts] = useState<PayoutRow[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [completingId, setCompletingId] = useState<string | null>(null);
  const [selectedPayout, setSelectedPayout] = useState<PayoutRow | null>(null);
  const [payoutDonations, setPayoutDonations] = useState<DonationRow[]>([]);
  const [loadingDonations, setLoadingDonations] = useState(false);

  const loadPayouts = useCallback(async () => {
    setIsLoading(true);
    try {
      const res = await fetch("/api/admin/payouts", { credentials: "include" });
      if (!res.ok) throw new Error("Failed to load payouts");
      const data = await res.json();
      const sorted = [...(data || [])].sort((a: PayoutRow, b: PayoutRow) => {
        const aPending = a.status === "pending" ? 1 : 0;
        const bPending = b.status === "pending" ? 1 : 0;
        if (bPending !== aPending) return bPending - aPending;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
      setPayouts(sorted);
    } catch (err) {
      console.error("Error loading payouts:", err);
      setPayouts([]);
      alert("Failed to load payouts.", { title: "Error", variant: "error" });
    } finally {
      setIsLoading(false);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps -- loadPayouts intentionally runs once on mount

  useEffect(() => {
    loadPayouts();
  }, [loadPayouts]);

  useEffect(() => {
    if (!selectedPayout) {
      setPayoutDonations([]);
      return;
    }
    let cancelled = false;
    setLoadingDonations(true);
    fetch(`/api/admin/data/donations?campaignId=${encodeURIComponent(selectedPayout.campaignId)}`, { credentials: "include" })
      .then((res) => (res.ok ? res.json() : []))
      .then((data) => {
        if (!cancelled) setPayoutDonations(Array.isArray(data) ? data : []);
      })
      .catch(() => {
        if (!cancelled) setPayoutDonations([]);
      })
      .finally(() => {
        if (!cancelled) setLoadingDonations(false);
      });
    return () => { cancelled = true; };
  }, [selectedPayout]);

  function openPayoutDetail(p: PayoutRow, e: React.MouseEvent) {
    if ((e.target as HTMLElement).closest("button")) return;
    setSelectedPayout(p);
  }

  function openPrintWindow(): Window | null {
    const win = window.open("", "_blank", "noopener,noreferrer");
    if (!win) {
      alert("Popup blocked. Allow popups to download or print the payout letter.", {
        title: "Popup blocked",
        variant: "info",
      });
      return null;
    }
    win.document.write(`<!doctype html><html><head><meta charset="utf-8" /><title>Preparing…</title></head><body style="font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;padding:24px;color:#111827;"><p>Preparing payout letter…</p></body></html>`);
    win.document.close();
    return win;
  }

  function writeHtmlAndPrint(win: Window, html: string) {
    win.document.open();
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  }

  function openPayoutLetterWindow(p: PayoutRow, donations: DonationRow[], existingWin?: Window | null) {
    const html = buildPayoutLetterHtml(p, donations);
    const win = existingWin ?? openPrintWindow();
    if (!win) return;
    writeHtmlAndPrint(win, html);
  }

  async function handleDownloadPdfFromRow(p: PayoutRow, e: React.MouseEvent) {
    e.stopPropagation();
    if (p.status !== "completed") {
      alert("A downloadable payout letter is available after the payout is marked as completed.", {
        title: "Not ready yet",
        variant: "info",
      });
      return;
    }
    // Open the window synchronously from the click event; fetching first can trigger popup blockers.
    const win = openPrintWindow();
    if (!win) return;
    try {
      const res = await fetch(`/api/admin/data/donations?campaignId=${encodeURIComponent(p.campaignId)}`, {
        credentials: "include",
      });
      const data = (await res.json().catch(() => [])) as unknown;
      const donations = Array.isArray(data) ? (data as DonationRow[]) : [];
      openPayoutLetterWindow(p, donations, win);
    } catch (err) {
      try {
        win.close();
      } catch {}
      console.error("Error opening payout letter:", err);
      alert("Failed to open payout letter. Please try again.", {
        title: "Error",
        variant: "error",
      });
    }
  }

  function handleDownloadPdfFromModal() {
    if (!selectedPayout) return;
    openPayoutLetterWindow(selectedPayout, payoutDonations);
  }

  async function handleComplete(id: string, e: React.MouseEvent) {
    e.stopPropagation();
    setCompletingId(id);
    try {
      const res = await fetch(`/api/admin/payouts/${id}/complete`, {
        method: "POST",
        credentials: "include",
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(typeof data.error === "string" ? data.error : "Failed to complete payout");
      }
      await loadPayouts();
      alert("Payout marked as completed. The creator has been notified by email and in-app.", {
        title: "Completed",
        variant: "success",
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Failed to complete payout";
      alert(msg, { title: "Error", variant: "error" });
    } finally {
      setCompletingId(null);
    }
  }

  const pendingCount = payouts.filter((p) => p.status === "pending").length;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4" />
          <p className="text-gray-600">Loading payouts...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-semibold text-gray-900 flex items-center gap-2">
            <Banknote className="w-8 h-8 text-primary-600" />
            Payouts
          </h1>
          <p className="text-gray-600 mt-1">
            {payouts.length} payout request{payouts.length !== 1 ? "s" : ""} total
            {pendingCount > 0 && (
              <span className="ml-2 text-amber-700 font-medium">
                · {pendingCount} pending
              </span>
            )}
          </p>
        </div>
      </div>

      {payouts.length === 0 ? (
        <div className="bg-white rounded-xl gradient-border-1 p-8 text-center text-gray-500">
          No payout requests yet.
        </div>
      ) : (
        <div className="bg-white rounded-xl gradient-border-1 min-w-0">
          <p className="px-4 py-2 text-xs text-gray-500 border-b border-gray-100 md:sr-only" aria-hidden="true">Scroll horizontally to view all columns.</p>
          <div className="overflow-x-auto min-w-0 w-full" style={{ WebkitOverflowScrolling: "touch" }}>
            <table className="w-full text-sm min-w-[980px] divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Campaign</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Creator</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Bank</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                  <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Invoice / Statement</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {payouts.map((p) => (
                  <tr
                    key={p.id}
                    className="hover:bg-gray-50/50 cursor-pointer"
                    onClick={(e) => openPayoutDetail(p, e)}
                  >
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span
                        className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          p.status === "pending"
                            ? "bg-amber-100 text-amber-800"
                            : p.status === "completed"
                              ? "bg-green-100 text-green-800"
                              : "bg-gray-100 text-gray-800"
                        }`}
                      >
                        {p.status === "pending" && "Pending"}
                        {p.status === "completed" && "Completed"}
                        {p.status === "processing" && "Processing"}
                        {p.status === "rejected" && "Rejected"}
                        {!["pending", "completed", "processing", "rejected"].includes(p.status) && p.status}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-gray-900 font-medium">{p.campaignTitle || "—"}</span>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700 font-medium">
                      {formatAmount(p.raised)}
                    </td>
                    <td className="px-4 py-3">
                      <div className="text-sm text-gray-900">{p.creatorName || "—"}</div>
                      <div className="text-xs text-gray-500">{p.creatorEmail || ""}</div>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-700">
                      <div>{p.bankName} · {p.accountType}</div>
                      <div className="text-xs text-gray-500">
                        {p.accountHolderName} · ****{String(p.accountNumber).slice(-4)}
                        {p.branch ? ` · ${p.branch}` : ""}
                      </div>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-500">
                      {formatDate(p.createdAt)}
                    </td>
                    <td className="px-4 py-3 text-center whitespace-nowrap">
                      {p.status === "completed" ? (
                        <button
                          type="button"
                          onClick={(e) => handleDownloadPdfFromRow(p, e)}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-300 text-gray-700 text-xs font-medium hover:bg-gray-50"
                        >
                          <FileDown className="w-4 h-4" />
                          <span className="hidden sm:inline">Download PDF</span>
                        </button>
                      ) : (
                        <span className="text-[11px] text-gray-400">After completion</span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-right whitespace-nowrap">
                      {p.status === "pending" ? (
                        <button
                          type="button"
                          onClick={(e) => handleComplete(p.id, e)}
                          disabled={completingId !== null}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-green-600 text-white text-sm font-medium hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {completingId === p.id ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <CheckCircle className="w-4 h-4" />
                          )}
                          Mark as completed
                        </button>
                      ) : (
                        <span className="text-gray-400 text-sm">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Payout detail modal */}
      {selectedPayout && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50" onClick={() => setSelectedPayout(null)}>
          <div
            className="bg-white rounded-xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Payout details</h2>
              <button
                type="button"
                onClick={() => setSelectedPayout(null)}
                className="p-2 rounded-lg text-gray-500 hover:bg-gray-100 hover:text-gray-700"
                aria-label="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="overflow-y-auto flex-1 p-4 space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                <p><span className="font-medium text-gray-500">Campaign</span><br />{selectedPayout.campaignTitle || "—"}</p>
                <p><span className="font-medium text-gray-500">Amount</span><br />{formatAmount(selectedPayout.raised)}</p>
                <p><span className="font-medium text-gray-500">Creator</span><br />{selectedPayout.creatorName || "—"} · {selectedPayout.creatorEmail || ""}</p>
                <p><span className="font-medium text-gray-500">Status</span><br /><span className="capitalize">{selectedPayout.status}</span></p>
                <p><span className="font-medium text-gray-500">Bank</span><br />{selectedPayout.bankName} · {selectedPayout.accountType}</p>
                <p><span className="font-medium text-gray-500">Account holder</span><br />{selectedPayout.accountHolderName}</p>
                <p><span className="font-medium text-gray-500">Account number</span><br />{selectedPayout.accountNumber}{selectedPayout.branch ? ` · ${selectedPayout.branch}` : ""}</p>
                <p><span className="font-medium text-gray-500">Request date</span><br />{formatDate(selectedPayout.createdAt)}</p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-700 mb-2">Payments made (donations)</h3>
                {loadingDonations ? (
                  <div className="flex items-center gap-2 text-gray-500 py-4">
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Loading…
                  </div>
                ) : payoutDonations.length === 0 ? (
                  <p className="text-sm text-gray-500 py-2">No donations found for this campaign.</p>
                ) : (
                  <div className="overflow-x-auto border border-gray-200 rounded-lg">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="px-3 py-2 text-left font-medium text-gray-600">Date</th>
                          <th className="px-3 py-2 text-left font-medium text-gray-600">Donor</th>
                          <th className="px-3 py-2 text-right font-medium text-gray-600">Amount</th>
                          <th className="px-3 py-2 text-left font-medium text-gray-600">Method</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200">
                        {payoutDonations.filter((d) => d.status === "completed").map((d) => (
                          <tr key={d.id}>
                            <td className="px-3 py-2 text-gray-600">{formatDate(d.createdAt)}</td>
                            <td className="px-3 py-2">{d.anonymous ? "Anonymous" : (d.donorName || d.donorEmail || "—")}</td>
                            <td className="px-3 py-2 text-right font-medium">{formatAmount(d.amount)}</td>
                            <td className="px-3 py-2 text-gray-600">{d.method || "—"}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
            <div className="flex flex-wrap items-center justify-end gap-2 px-4 py-3 border-t border-gray-200 bg-gray-50">
              {selectedPayout.status === "completed" ? (
                <button
                  type="button"
                  onClick={handleDownloadPdfFromModal}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary-600 text-white text-sm font-medium hover:bg-primary-700"
                >
                  <FileDown className="w-4 h-4" />
                  Download PDF
                </button>
              ) : (
                <span className="text-xs text-gray-500 mr-auto">
                  A printable payout letter will be available after this payout is marked as completed.
                </span>
              )}
              <button
                type="button"
                onClick={() => setSelectedPayout(null)}
                className="px-4 py-2 rounded-lg border border-gray-300 text-gray-700 text-sm font-medium hover:bg-gray-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
