-- Add 4 fictional Little Warriors campaigns (paired images: y, x, v, a).
-- NOTE: these rows expect matching files in /public/little-warriors/
-- with names y1.jpg, y2.jpg, x1.jpg, x2.jpeg, v1.jpg, v2.jpg, a1.jpg, a2.jpg.

insert into public.campaigns (
  id,
  title,
  description,
  full_description,
  creator,
  creator_type,
  creator_id,
  goal,
  raised,
  backers,
  days_left,
  category,
  image,
  image2,
  location,
  status,
  verified,
  admin_backed,
  is_little_warriors,
  created_at,
  updated_at
)
values
(
  '74f4f4d2-73a8-4ad9-8e3d-2f8f30f29601',
  'Help Mia Recover From Severe Viral Fever',
  '7-year-old Mia needs urgent tests, medication, and follow-up care after repeated high fevers.',
  'Mia has been admitted multiple times with persistent high fever and dehydration. Her family is trying to cover lab work, pediatric specialist visits, and medication, but costs keep increasing. This campaign will help with diagnostics, treatment, and transportation to follow-up appointments so Mia can recover safely.',
  'Mia''s Family Support Circle',
  'individual',
  null,
  8200,
  2630,
  49,
  23,
  'Medical expenses',
  '/little-warriors/y1.jpg',
  '/little-warriors/y2.jpg',
  'Belmopan, Belize',
  'live',
  true,
  false,
  true,
  now(),
  now()
),
(
  '74f4f4d2-73a8-4ad9-8e3d-2f8f30f29602',
  'Breathing Support for Jayden''s ICU Recovery',
  'Jayden is fighting a serious respiratory infection and needs ICU support and post-discharge therapy.',
  'Little Jayden was placed on breathing support after a severe respiratory infection. His doctors expect a long recovery period with hospital monitoring, respiratory therapy, and medications after discharge. Funds raised will go directly to ICU-related costs, medications, and recovery care for Jayden.',
  'Jayden Recovery Team',
  'individual',
  null,
  9700,
  3415,
  62,
  19,
  'Medical expenses',
  '/little-warriors/x1.jpg',
  '/little-warriors/x2.jpeg',
  'Orange Walk Town, Belize',
  'live',
  true,
  false,
  true,
  now(),
  now()
),
(
  '74f4f4d2-73a8-4ad9-8e3d-2f8f30f29603',
  'Cold & Chest Treatment Fund for Alina',
  'Alina needs pediatric care, medication, and monitoring for recurring chest infections.',
  'Alina has been experiencing recurring flu-like symptoms and chest complications that require close pediatric follow-up. Her family needs support for clinic visits, medicine, and emergency checkups to prevent complications. Your help can keep Alina on track to a full recovery.',
  'Friends of Alina',
  'individual',
  null,
  7600,
  1890,
  37,
  27,
  'Medical expenses',
  '/little-warriors/v1.jpg',
  '/little-warriors/v2.jpg',
  'Dangriga, Belize',
  'live',
  true,
  false,
  true,
  now(),
  now()
),
(
  '74f4f4d2-73a8-4ad9-8e3d-2f8f30f29604',
  'Emergency Pediatric Oxygen Care for Nyla',
  'Nyla urgently needs oxygen therapy, specialist review, and continued pediatric treatment.',
  'Nyla was rushed in with breathing distress and now requires oxygen support and continued pediatric supervision. Her mother is doing everything possible, but hospital bills and treatment costs are overwhelming. This fundraiser will help cover oxygen therapy, medicine, and specialist follow-up care for Nyla.',
  'Nyla Care Fund',
  'individual',
  null,
  10300,
  4120,
  71,
  16,
  'Medical expenses',
  '/little-warriors/a1.jpg',
  '/little-warriors/a2.jpg',
  'San Ignacio, Cayo District, Belize',
  'live',
  true,
  false,
  true,
  now(),
  now()
)
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  full_description = excluded.full_description,
  creator = excluded.creator,
  creator_type = excluded.creator_type,
  goal = excluded.goal,
  raised = excluded.raised,
  backers = excluded.backers,
  days_left = excluded.days_left,
  category = excluded.category,
  image = excluded.image,
  image2 = excluded.image2,
  location = excluded.location,
  status = excluded.status,
  verified = excluded.verified,
  admin_backed = excluded.admin_backed,
  is_little_warriors = excluded.is_little_warriors,
  updated_at = now();
